version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: taskdb-container
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"

  backend:
    build: ./
    container_name: tasktracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass
    depends_on:
      - postgres

  frontend:
    build: ./task-tracker-frontend
    container_name: tasktracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
